### ISSUE TITLE
Mox Pearl, Ruby etc... not part of mana calculation

### ISSUE THREAD

**Issue by mmussmann** [mtgoncurve/mtgoncurve.com#28]
Shouldn't moxes be part of the mana calculation?

**Comment by jshrake** [comment]
They should, but the project is currently in maintenance mode and I do not intend to add this feature. You can manually make these cards count as mana by appending a string like `#M = {R}{G}{B}{U}{W}{1}` to the end of the card in the deck list. Keep in mind that this will treat the card as a land card and ignore the cost to cast them. See the Advanced section for more details https://mtgoncurve.com/about.
