### ISSUE TITLE
Missing Card - Osgir, the Reconstructor

### ISSUE THREAD

**Issue by Fingersniffer** [mtgoncurve/mtgoncurve.com#35]
Osgir, the Reconstructor

Error running simulation for input: BadDeckcode( "Cannot find card named \"Osgir, the Reconstructor\" in collection", )

**Comment by jshrake** [comment]
Fixed by https://github.com/mtgoncurve/mtgoncurve.com/pull/36. Thanks for the report!

![image](https://user-images.githubusercontent.com/3046816/118214157-163f4680-b424-11eb-95ac-3735b5a16058.png)
