### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by MarcusAseth** [mtgoncurve/mtgoncurve.com#39]
Hi, I have 2 questions about mtg on curve

First question is: lets say I load a 60 deck card and I have an "Expected lands in opening hand" of 2.71 but then I add 200 Mountains to it, and "Expected lands in opening hand" becomes 4.33
This seems like a bug, unless I'm misunderstanding the meaning of "Expected lands in opening hand", can you explain it?

Second question is: lets say I load another deck which contains 3 Wicked Wolf and given my current lands setup, the "P play" value is 12.9   
Now I add 100 more forests to it, and the "P play" goes up to 20.5... is this really correct? With 100 extra cards in the deck one would assume now is near impossible for one of those 3 Wolves to show up by turn 4
Is this a bug or there is an explanation?

**Comment by jshrake** [comment]
> First question is: lets say I load a 60 deck card and I have an "Expected lands in opening hand" of 2.71 but then I add 200 Mountains to it, and "Expected lands in opening hand" becomes 4.33
This seems like a bug, unless I'm misunderstanding the meaning of "Expected lands in opening hand", can you explain it?

The simulation takes into account the mulligan process and has a crude mulligan strategy that you can configure below your deck list. By default, the simulator will mulligan away hands containing too few or too many lands.

> Second question is: lets say I load another deck which contains 3 Wicked Wolf and given my current lands setup, the "P play" value is 12.9. Now I add 100 more forests to it, and the "P play" goes up to 20.5... is this really correct? With 100 extra cards in the deck one would assume now is near impossible for one of those 3 Wolves to show up by turn 4. Is this a bug or there is an explanation?

The mulligan strategy would also impact this result. Past a certain number of lands, the "P play" value essentially becomes the probability of drawing at least one copy of that card by that turn.

You can force the simulator to behave like a hypergeometric calculator by selecting the `No Mulligan` option from the London Mulligan Strategy dropdown, and compare the results to a (multivariate) hypergeometric distribution. The simulator has some test cases around this https://github.com/mtgoncurve/landlord/blob/ce9181a3016d678c02f83fa57e8aec342a8be114/lib/src/simulation.rs
