### ISSUE TITLE
Expected values?

### ISSUE THREAD

**Issue by juj** [mtgoncurve/mtgoncurve.com#44]
Hi, interesting project 👍 

I was looking at an old white weenie deck,

https://mtgoncurve.com/?v0=eyJjb2RlIjoiNCBUdW5kcmEgV29sdmVzXG40IEJlbmFsaXNoIEhlcm9cbjQgTWVzYSBQZWdhc3VzXG4yIFBpa2VtZW5cbjQgV2hpdGUgS25pZ2h0XG40IFNhdmFubmFoIExpb25zXG4yIFNlcnJhIEFuZ2VsXG40IEhvbHkgU3RyZW5ndGhcbjQgU3Bpcml0IExpbmtcbjQgQ3J1c2FkZVxuNCBCbGVzc2luZ1xuMyBEaXZpbmUgVHJhbnNmb3JtYXRpb25cbjE3IFBsYWluc1xuIiwib25fdGhlX3BsYXkiOnRydWUsImluaXRpYWxfaGFuZF9zaXplIjo3LCJtdWxsaWdhbl9kb3duX3RvIjo1LCJtdWxsaWdhbl9vbl9sYW5kcyI6WzAsNSw2LDcsMV0sImNhcmRzX3RvX2tlZXAiOiIifQ%3D%3D#

which decided to take a slightly lower count of 17 white lands, but at the same time, take three Divine Transformations and two Serras as "end game" creatures in case the game would drag on.

So when using the calculator to figure out the question "is 17 lands the right number of lands for this kind of deck?" and "does it make any sense to have the two Serras in the deck with this little mana", there were two interesting questions that came up:

- the calculator shows that the probability of having 5 mana on turn 5 is 18.09%. What would the probability of having 5 mana on turn 6, or turn 7, etc. be? Or rather, the expected value of which turn one will have 5 mana available? In other words, maybe the calculator could display for each `k`, what is the expected turn number that the player will have `k` mana available?
- similarly, the probability to play Serra on turn 5 is shown to be 4.34%. So it is unlikely that Serra will appear on that turn, but what is then the expected value of the turn number that Serra Angel will come to play? (is it an expected turn 8 creature? Or an expected turn 15 creature? etc.) It might be interesting for the calculator to show for each card, the EV of which turn that card will first appear on board.

Cheers :)

**Comment by jshrake** [comment]
Great questions! The simulation can calculate the probability to play a card on a specific turn by appending `# T = k` to the card (see the Advanced section at https://mtgoncurve.com/about). In the image below, the simulation calculates the probability to play Thought Erasure on turn 4.

![image](https://user-images.githubusercontent.com/3046816/165215466-eaa8a114-5c39-4fe0-8135-dc83f7586864.png)
