### ISSUE TITLE
DMU Update?

### ISSUE THREAD

**Issue by rstad** [mtgoncurve/mtgoncurve.com#61]
I'm not really sure if this is the best way to ask about it, and if this is something that I should be submitting a PR for somehow I am happy to spend some time figuring that out.

**Comment by jshrake** [comment]
Done and deployed with https://github.com/mtgoncurve/mtgoncurve.com/pull/62.

Thanks to @jshill103 for the update https://github.com/mtgoncurve/landlord/pull/44
