### ISSUE TITLE
Website Seems Borked?

### ISSUE THREAD

**Issue by BlobfishXL** [mtgoncurve/mtgoncurve.com#70]
![Screenshot 2023-01-11 114433](https://user-images.githubusercontent.com/122484054/211902797-97a99259-6e98-4dc3-b7d4-4dbd1191063d.png)

Something seems wrong (maybe user error!) I seem to only be able to get the site to return a probability of 100 or 0. Using chrome on win 11. Screenshot attached.

**Comment by jshrake** [comment]
The results look correct given your inputs. You can hover over the column names in the results table to see a tooltip with more information.

- P(mana|turn) is the conditional probability to draw the appropriate mana by turn N, conditional on drawing at least N mana sources. Given your inputs, a value of 100% would be expected -- if you have 5 lands in hand, then you can always play the card.
- P(mana) is the probability to actually draw 5 lands by turn 5, which is small given your inputs.
- P(play) is the probability to draw the card and draw sufficient lands by turn 5, which again is small given your inputs.

**Comment by BlobfishXL** [comment]
Sorry I misunderstood what the blue meant! Thank you for the kind clarification
