### ISSUE TITLE
Cannot find cards named Sigarda and Nissa

### ISSUE THREAD

**Issue by vcfdre43** [mtgoncurve/mtgoncurve.com#73]
Sigarda, Font of Blessings
Nissa, Resurgent Animist

Error running simulation for input: BadDeckcode( "Cannot find card named \"Sigarda, Font of Blessings\" in collection", )
Error running simulation for input: BadDeckcode( "Cannot find card named \"Nissa, Resurgent Animist\" in collection", )

**Comment by killkong1211** [comment]
It seems like aftermath hasn't been added as yet.

Would probably be a fair rewrite but would suggest leveraging the Scryfall API for card information to remove the necessity of manual updates.

**Comment by jshrake** [comment]
Closed by #74

> Would probably be a fair rewrite but would suggest leveraging the Scryfall API for card information to remove the necessity of manual updates.

It's possible to automate the card updates, but I just don't have the time or interest in this game anymore to do that work. The reason the way it works today is for performance and to allow the app to function offline after the first page load.
