### ISSUE TITLE
Could you describe "on the play" a bit more on the about page?

### ISSUE THREAD

**Issue by savanaben** [mtgoncurve/mtgoncurve.com#81]
I just wanted to request if you could describe what "on the play" means a bit more. After running calculations comparing the simulation against a hypergeometric simulation I think I've finally understood that it is sort of showing a calculation of casting the card a turn earlier?  Thanks!

**Comment by savanaben** [comment]
One more comment. I also wanted to thank you for your work on this - it's been inspiring, and your tool is the only one I've found that's been able to confirm advanced mana probabilities I've been working on in my tool. 

I was wondering, do you think it'd be more helpful for people to highlight rows in blue when the "P mana" value is over 90%, vs. the "P mana/turn" value? Maybe I'm not understanding something... I see the concept of casting something on curve as being able to cast that spell on the earliest turn I can (casting a 3cmc spell on turn 3). Since the P mana/turn is "conditional on drawing at least N mana sources", does that mean it assumes you'll always have enough mana sources (and is just focused on making the right colors?). If that's true, I'm not sure how representative that is to a concept of "on curve" (does on curve mean I have the right colors and the right amount of land to cast a 3 cmc spell on turn 3). 

Thanks again and awesome job. I have no idea what magical logic you use to run 1,000,000 iterations so quickly. I can hardly run 10,000 without 5-10s of loading.

**Comment by dvndrsn** [comment]
This also confused me at first a little. From my understanding, "on the play" describes how you start your first turn of the game with play first ("on the play") or draw first ("on the draw") rules.

I'm suggesting PR #88 to try to refactor the UI to try to make this more intuitive.
